"""The scene stage: every location's prose, choices and open question at once.

This is one batched call rather than one call per location, for a reason that
shows up directly in the game: five sequential calls would put four of them on
the loading screen or make the player wait mid-walk, and a model that writes
all five scenes together stops repeating the same opening image in each one.

Which choice is "on canon" is decided here and kept server-side. The player
sees three equal options; only the ending knows which way the story leaned.
"""

from pydantic import BaseModel, Field

from app.llm.base import LLM
from app.models.game import Choice, Language, SafetyClass, Scene, StyleCard
from app.models.plan import CHOICES_PER_SCENE, ChoiceDraft, ScenesDraft, StoryPlan
from app.models.script import ChoiceOutcome
from app.pipeline.prompts import MARKER_RULE, SAFE_MODE_RULE, language_rule, style_block
from app.pipeline.style_card import style_prompt

STAGE = "scenes"

#: Scene prose length, in sentences. Long enough to be worth reading, short
#: enough that five of them plus the walking fit inside ten minutes.
MIN_SENTENCES, MAX_SENTENCES = 3, 5


class SceneBundle(BaseModel):
    """Everything the turn engine needs, keyed by location id."""

    scenes: dict[str, Scene] = Field(default_factory=dict)
    choices: dict[str, list[Choice]] = Field(default_factory=dict)
    outcomes: dict[str, ChoiceOutcome] = Field(default_factory=dict)
    open_questions: dict[str, str] = Field(default_factory=dict)


def _instructions(language: Language, safety_class: SafetyClass) -> str:
    safe = f"\n\nSAFETY:\n{SAFE_MODE_RULE}" if safety_class == "safe_mode" else ""
    return f"""You write the scenes of a short interactive story. The player arrives at \
each location once, reads what is there, and picks one of three actions.

{language_rule(language)}

For every location in the plan, in order, return one scene with:
- `location_index`: the index of the location in the plan, starting at 0.
- `text`: {MIN_SENTENCES} to {MAX_SENTENCES} sentences. Second person or the voice the \
style asks for. Describe what the player finds *now*, including anyone present and what \
they are doing. Do not describe the player walking here, do not recap earlier scenes, \
and never mention choices, turns, the map or the game.
- `choices`: exactly {CHOICES_PER_SCENE}, each 3 to 9 words, each a different kind of \
action - not three phrasings of one. A choice is something the player does or says here \
and now. Each carries a `consequence`: one clause, in the story language, saying what it \
leads to. Set `on_canon` true on the choice that moves the planned beat forward and \
false on choices that step away from it. At least one must be true and at least one \
false.
- `open_question`: only for the locations listed as asking one. It is a question in the \
story's voice that the player answers by typing a sentence - "What do you tell her?", \
not "Choose an option". Leave it as an empty string everywhere else.

{MARKER_RULE}{safe}"""


def _brief(plan: StoryPlan) -> str:
    lines = [f"TITLE: {plan.title}", f"PREMISE: {plan.premise}", "", "LOCATIONS:"]
    for index, location in enumerate(plan.locations):
        asks = " [asks an open question]" if location.id in plan.open_question_at else ""
        lines.append(f"{index}. {location.name}{asks} - {location.description}")
    if plan.beats:
        lines += ["", "WHAT HAPPENS, IN ORDER:"]
        for beat in plan.beats:
            where = next((loc.name for loc in plan.locations if loc.id == beat.location_ref), "")
            lines.append(f"- ({where}) {beat.title}: {beat.summary}")
    return "\n".join(lines)


async def write_scenes(
    llm: LLM,
    plan: StoryPlan,
    *,
    style: StyleCard,
    safety_class: SafetyClass = "allowed",
) -> SceneBundle:
    draft = await llm.json(
        STAGE,
        f"{style_block(style_prompt(style))}\n\n{_brief(plan)}",
        ScenesDraft,
        system=_instructions(plan.language, safety_class),
    )
    return assemble(draft, plan)


def assemble(draft: ScenesDraft, plan: StoryPlan) -> SceneBundle:
    """Bind a positional draft to location ids, and fill any gaps it left.

    A location with no scene would be a dead end the player can walk into, so
    a missing one falls back to its own planned description rather than being
    dropped from the map - the map is already generated by the time anyone
    could react to a short scene list.
    """
    bundle = SceneBundle()
    by_index = {d.location_index: d for d in draft.scenes}

    for index, location in enumerate(plan.locations):
        item = by_index.get(index)
        text = (item.text.strip() if item else "") or location.description
        bundle.scenes[location.id] = Scene(
            id=f"scene-{location.id}", location_id=location.id, text=text
        )

        drafted = [c for c in (item.choices if item else []) if c.text.strip()][:CHOICES_PER_SCENE]
        # A location with no choices cannot be resolved, so the player would
        # be stuck on the map with a destination they can never finish.
        drafted = drafted or _fallback_choices(plan.language)

        beat = next((b for b in plan.beats if b.location_ref == location.id), None)
        choices: list[Choice] = []
        for position, option in enumerate(drafted):
            choice_id = f"{location.id}-c{position + 1}"
            choices.append(Choice(id=choice_id, text=option.text.strip()))
            bundle.outcomes[choice_id] = ChoiceOutcome(
                beat_id=beat.id if beat else None,
                on_canon=option.on_canon,
                consequence=option.consequence.strip(),
            )
        bundle.choices[location.id] = choices

        question = item.open_question.strip() if item else ""
        if question and location.id in plan.open_question_at:
            bundle.open_questions[location.id] = question

    # The plan asked for questions somewhere; honour that even if the scene
    # stage forgot, so the mechanic does not silently vanish from a run.
    for location_id in plan.open_question_at:
        bundle.open_questions.setdefault(location_id, _fallback_question(plan.language))
    return bundle


def _fallback_question(language: Language) -> str:
    return "Co robisz?" if language == "pl" else "What do you do?"


#: Deliberately bland, because they are only ever reached when generation has
#: failed twice. A dull choice is a playable game; no choice is a dead end.
_FALLBACK_CHOICES: dict[Language, list[str]] = {
    "pl": ["Rozejrzyj się uważnie", "Odezwij się pierwszy", "Ruszaj dalej"],
    "en": ["Look around carefully", "Speak first", "Move on"],
}


def _fallback_choices(language: Language) -> list[ChoiceDraft]:
    return [
        ChoiceDraft(text=text, consequence="", on_canon=index == 0)
        for index, text in enumerate(_FALLBACK_CHOICES[language])
    ]
