/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Verifies the token and enforces the invite list before the menu opens.
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_api_games_get"];
        put?: never;
        /** Create Game */
        post: operations["create_game_api_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Coarse loading progress, and the only place a generation failure surfaces.
         *
         *     Deliberately does not load the game first: under live generation the state
         *     does not exist yet when the client subscribes, which is the entire reason
         *     this stream exists.
         */
        get: operations["stream_api_games__game_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move */
        post: operations["move_api_games__game_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/choose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose */
        post: operations["choose_api_games__game_id__choose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_api_games__game_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/set-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Off */
        post: operations["set_off_api_games__game_id__set_off_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/ending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ending */
        get: operations["ending_api_games__game_id__ending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay */
        get: operations["replay_api_games__game_id__replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerRequest */
        AnswerRequest: {
            /** Text */
            text: string;
        };
        /**
         * ApiError
         * @description Every failure the UI can show. `kind` is what the client branches on.
         */
        ApiError: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "network" | "generation_failed" | "pool_empty" | "budget_exceeded" | "blocked_event" | "auth";
            /** Detail */
            detail: string;
        };
        /** BeatProgress */
        BeatProgress: {
            /** Beat Id */
            beat_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "matched" | "diverged" | "skipped";
        };
        /** CanonBeat */
        CanonBeat: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Sources */
            sources?: string[];
        };
        /** Choice */
        Choice: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** ChooseRequest */
        ChooseRequest: {
            /** Choice Id */
            choice_id: string;
        };
        /** Destination */
        Destination: {
            /** Key */
            key: string;
            /** Location Id */
            location_id: string;
            /** Name */
            name: string;
        };
        /** Door */
        Door: {
            /** Key */
            key: string;
            pos: components["schemas"]["Pos"];
            /** Unlock From */
            unlock_from: string;
        };
        /** EndingComparison */
        EndingComparison: {
            /** Game Id */
            game_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "idea" | "news";
            /** Match Score */
            match_score?: number | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Canon */
            canon?: components["schemas"]["CanonBeat"][];
            /** Player */
            player?: components["schemas"]["PlayerBeat"][];
            style_card: components["schemas"]["StyleCard"];
            /** Style Labels */
            style_labels?: components["schemas"]["StyleLabel"][];
            /** Sources */
            sources?: components["schemas"]["SourceLink"][];
        };
        /**
         * GameMap
         * @description Tile grid. `#` wall, `.` floor, `+` locked door, `@` start, `A`-`E` destinations.
         */
        GameMap: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Tiles */
            tiles: string[];
            /** Destinations */
            destinations: components["schemas"]["Destination"][];
            /** Doors */
            doors?: components["schemas"]["Door"][];
        };
        /** GameState */
        GameState: {
            /** Game Id */
            game_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "idea" | "news";
            /**
             * View
             * @default scene
             * @enum {string}
             */
            view: "travel" | "scene";
            /** Region */
            region?: ("pl" | "world") | null;
            /**
             * Story Language
             * @enum {string}
             */
            story_language: "pl" | "en";
            /**
             * Ui Language
             * @enum {string}
             */
            ui_language: "pl" | "en";
            /**
             * Safety Class
             * @default allowed
             * @enum {string}
             */
            safety_class: "allowed" | "safe_mode" | "blocked";
            /** Content Note */
            content_note?: string | null;
            /** Source Note */
            source_note?: string | null;
            style_card: components["schemas"]["StyleCard"];
            map: components["schemas"]["GameMap"];
            player_pos: components["schemas"]["Pos"];
            /** Visited */
            visited?: string[];
            /** Resolved */
            resolved?: string[];
            /** Unlocked */
            unlocked?: string[];
            current_scene: components["schemas"]["Scene"];
            /** Choices */
            choices?: components["schemas"]["Choice"][];
            open_question?: components["schemas"]["OpenQuestion"] | null;
            /** Beat Progress */
            beat_progress?: components["schemas"]["BeatProgress"][];
            /**
             * Divergence
             * @default 0
             */
            divergence: number;
            /**
             * Turn
             * @default 0
             */
            turn: number;
            /**
             * Finished
             * @default false
             */
            finished: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Llm Mode */
            llm_mode: string;
            /** Music Mode */
            music_mode: string;
            /** Auth Mode */
            auth_mode: string;
        };
        /** ImageCredit */
        ImageCredit: {
            /** Source Url */
            source_url: string;
            /** Credit */
            credit: string;
        };
        /** Me */
        Me: {
            /** Uid */
            uid: string;
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
        };
        /** MoveRequest */
        MoveRequest: {
            to: components["schemas"]["Pos"];
        };
        /** NewGameRequest */
        NewGameRequest: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "idea" | "news";
            /** Idea */
            idea?: string | null;
            /** Region */
            region?: ("pl" | "world") | null;
            /**
             * Story Language
             * @enum {string}
             */
            story_language: "pl" | "en";
            /**
             * Ui Language
             * @enum {string}
             */
            ui_language: "pl" | "en";
        };
        /** NewGameResponse */
        NewGameResponse: {
            /** Game Id */
            game_id: string;
        };
        /** OpenQuestion */
        OpenQuestion: {
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
        };
        /** PlayerBeat */
        PlayerBeat: {
            /** Beat Id */
            beat_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "matched" | "diverged" | "skipped";
            /** What You Did */
            what_you_did: string;
        };
        /** Pos */
        Pos: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** Replay */
        Replay: {
            /** Game Id */
            game_id: string;
            /** Title */
            title: string;
            /** Turns */
            turns?: components["schemas"]["ReplayTurn"][];
        };
        /** ReplayTurn */
        ReplayTurn: {
            /** Turn */
            turn: number;
            scene: components["schemas"]["Scene"];
            player_pos: components["schemas"]["Pos"];
            /** Chosen */
            chosen?: string | null;
            /** Answer */
            answer?: string | null;
        };
        /** SavedGame */
        SavedGame: {
            /** Game Id */
            game_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "idea" | "news";
            /** Region */
            region?: ("pl" | "world") | null;
            /** Title */
            title: string;
            /** Played At */
            played_at: string;
            /**
             * Story Language
             * @enum {string}
             */
            story_language: "pl" | "en";
            /** Match Score */
            match_score?: number | null;
            /** Image Url */
            image_url?: string | null;
        };
        /** Scene */
        Scene: {
            /** Id */
            id: string;
            /** Location Id */
            location_id: string;
            /** Text */
            text: string;
            /** Image Url */
            image_url?: string | null;
            image_credit?: components["schemas"]["ImageCredit"] | null;
        };
        /** SourceLink */
        SourceLink: {
            /** Url */
            url: string;
            /** Title */
            title: string;
        };
        /**
         * StageEvent
         * @description One SSE frame from the loading stream.
         *
         *     A load emits `stage` several times and then either `ready` or an `error`.
         *     All three shapes are declared on one model so the generated client has a
         *     single thing to parse.
         */
        StageEvent: {
            /** Stage */
            stage?: ("story" | "map" | "images" | "music" | "finishing") | null;
            /**
             * Ready
             * @default false
             */
            ready: boolean;
            error?: components["schemas"]["ApiError"] | null;
        };
        /** StyleCard */
        StyleCard: {
            /** Genre */
            genre: string;
            /** Narrative Voice */
            narrative_voice: string;
            /** Tone */
            tone: string;
            /** Protagonist Role */
            protagonist_role: string;
            /** Visual Style */
            visual_style: string;
            /** Music Mood */
            music_mood: string;
            /** Pacing */
            pacing: string;
        };
        /**
         * StyleLabel
         * @description One axis of the style card, already translated for the player.
         *
         *     The catalog that knows how to say "ink wash" in Polish lives on the
         *     backend, so the labels are sent rather than the raw enum ids.
         */
        StyleLabel: {
            /** Axis */
            axis: string;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    list_games_api_games_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedGame"][];
                };
            };
        };
    };
    create_game_api_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewGameResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    stream_api_games__game_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_api_games__game_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    choose_api_games__game_id__choose_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChooseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_games__game_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_off_api_games__game_id__set_off_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ending_api_games__game_id__ending_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndingComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_api_games__game_id__replay_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Replay"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
