/**
 * Game types, projected from the backend's OpenAPI schema.
 *
 * `src/api/schema.d.ts` is generated by `bun run gen:api` and is the single
 * source of truth - nothing here invents a shape. The intersections below only
 * re-assert collections that Pydantic's `default_factory` makes optional in the
 * schema but that the server always sends.
 */

import type { components } from './api/schema';

type S = components['schemas'];

export type Mode = S['GameState']['mode'];
export type Region = NonNullable<S['GameState']['region']>;
export type Language = S['GameState']['story_language'];
export type SafetyClass = S['GameState']['safety_class'];
export type View = S['GameState']['view'];
export type BeatStatus = S['BeatProgress']['status'];

/** Coarse progress enum; the UI only ever shows a vague label for these. */
export type Stage = NonNullable<S['StageEvent']['stage']>;

export type StyleCard = S['StyleCard'];
export type Pos = S['Pos'];
export type Destination = S['Destination'];
export type Door = S['Door'];
export type ImageCredit = S['ImageCredit'];
export type Scene = S['Scene'];
export type Choice = S['Choice'];
export type OpenQuestion = S['OpenQuestion'];
export type BeatProgress = S['BeatProgress'];
export type CanonBeat = S['CanonBeat'] & { sources: string[] };
export type PlayerBeat = S['PlayerBeat'];
export type SourceLink = S['SourceLink'];
export type StyleLabel = S['StyleLabel'];
export type ReplayTurn = S['ReplayTurn'];
export type SavedGame = S['SavedGame'];
export type NewGameRequest = S['NewGameRequest'];
export type User = S['Me'];

export type GameMap = S['GameMap'] & { doors: Door[] };

export type GameState = S['GameState'] & {
  map: GameMap;
  visited: string[];
  resolved: string[];
  unlocked: string[];
  choices: Choice[];
  beat_progress: BeatProgress[];
};

export type EndingComparison = S['EndingComparison'] & {
  canon: CanonBeat[];
  player: PlayerBeat[];
  style_labels: StyleLabel[];
  sources: SourceLink[];
};

export type Replay = S['Replay'] & { turns: ReplayTurn[] };

export type AppErrorKind = S['ApiError']['kind'];

export interface AppError {
  kind: AppErrorKind;
  detail?: string;
}
